// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuVfEN0hRJ793d4iJZ7VNgnlyAk6KQXQo',
    appId: '1:667289785663:web:29acb38d1e1dca8a0baf8a',
    messagingSenderId: '667289785663',
    projectId: 'success-planner-438c1',
    authDomain: 'success-planner-438c1.firebaseapp.com',
    storageBucket: 'success-planner-438c1.appspot.com',
    measurementId: 'G-LNFG4RHHTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI1FyvP7YDd2R6UD7jlxhk_8qkkXlsyhg',
    appId: '1:667289785663:android:c384b79dff456f1c0baf8a',
    messagingSenderId: '667289785663',
    projectId: 'success-planner-438c1',
    storageBucket: 'success-planner-438c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrjeSBMnxdNx-4k913RBA0D8kDtyOHh-k',
    appId: '1:667289785663:ios:3d9a757957e15a140baf8a',
    messagingSenderId: '667289785663',
    projectId: 'success-planner-438c1',
    storageBucket: 'success-planner-438c1.appspot.com',
    iosClientId: '667289785663-aq93gd6q63hf01ofe3ll2lflmk2kps9n.apps.googleusercontent.com',
    iosBundleId: 'de.ngproductions.successPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrjeSBMnxdNx-4k913RBA0D8kDtyOHh-k',
    appId: '1:667289785663:ios:3d9a757957e15a140baf8a',
    messagingSenderId: '667289785663',
    projectId: 'success-planner-438c1',
    storageBucket: 'success-planner-438c1.appspot.com',
    iosClientId: '667289785663-aq93gd6q63hf01ofe3ll2lflmk2kps9n.apps.googleusercontent.com',
    iosBundleId: 'de.ngproductions.successPlanner',
  );
}
